dataset: imagenet
num_classes: 1000
img_size: 224
dim: 768
patch_size: 16
num_heads: 8
mlp_ratio: 4
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
interpolation: bicubic
train_interpolation: bicubic
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: const
amp: True
batch_size: 24
val_batch_size: 24
lr: 5e-4
min_lr: 0.00001
sched: cosine
weight_decay: 5e-2
epochs: 300
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr: 0.000001
opt: adamw
smoothing: 0.1
workers: 8
depths: 8
#resume: /media/data/models/Spikingformer-CML-git-model/CML_768_model_best.pth.tar
